[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn frete_app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "."